apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::343540011649:role/eksctl-brain-cluster-nodegroup-ng--NodeInstanceRole-Lx0oeQ2Wj0xP
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

    - rolearn: arn:aws:iam::343540011649:role/codebuild-newproject-service-role
      username: codebuild
      groups:
        - system:masters
