version: 0.2

phases:
  pre_build:
    commands:
      # Login to ECR
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 343540011649.dkr.ecr.ap-south-1.amazonaws.com

      # Create unique version (auto)
      - IMAGE_TAG=$(date +%s)

  build:
    commands:
      # Build Docker image
      - docker build -t brain-tasks-app .

      # Tag with version
      - docker tag brain-tasks-app:latest 343540011649.dkr.ecr.ap-south-1.amazonaws.com/brain-task:$IMAGE_TAG

  post_build:
    commands:
      # Push to ECR
      - docker push 343540011649.dkr.ecr.ap-south-1.amazonaws.com/brain-task:$IMAGE_TAG

      # Update Kubernetes deployment
      - kubectl set image deployment/brain-deployment \
        brain-container=343540011649.dkr.ecr.ap-south-1.amazonaws.com/brain-task:$IMAGE_TAG
      - aws eks update-kubeconfig --region ap-south-1 --name brain-cluster
