apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-task
  template:
    metadata:
      labels:
        app: brain-task
    spec:
      containers:
      - name: brain-tasks-deployment
        image: 343540011649.dkr.ecr.ap-south-1.amazonaws.com/brain-task:latest
        ports:
          - containerPort: 80
